### ISSUE TITLE
What is userHome?

### ISSUE THREAD

**Issue by CMCDragonkai** [kamilchm/.nixpkgs#1]
In your `gtk-config`, you have `userHome`. Is that just a directory inside `/nix/store`, or is that somehow substituted into your `~` directory? How do you get your custom package configuration into your home, since everything is usually installed into `/nix/store`?

**Comment by kamilchm** [comment]
Sorry for late answer, I didn't get notification :/
I've added basic instruction how I use it in [README.md](https://github.com/kamilchm/.nixpkgs/blob/master/README.md).
Nothing fancy but gets job done, so I didn't bother to automate it more.

**Comment by kamilchm** [comment]
I've created installation script in https://github.com/kamilchm/.nixpkgs/blob/master/install.sh and updated README.
